name: Generate Repository Metrics

on:
  # Roda sempre que houver um push na branch 'main'
  push:
    branches:
      - main
  # Também roda uma vez por dia para manter atualizado
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para o bot salvar a imagem no repositório

    steps:
      - name: Generate repository metrics
        uses: lowlighter/metrics@latest
        with:
          # Nome do arquivo de imagem que será gerado
          filename: metrics.languages.svg

          # Token para que a action possa ler os dados do seu repositório
          token: ${{ secrets.GITHUB_TOKEN }}

          # Plugins e configurações
          base: "" # Não queremos os gráficos padrão, apenas o de linguagens
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage # Mostra o % de uso
          plugin_languages_limit: 8 # Mostra as 8 linguagens mais usadas
          plugin_languages_ignored: >- # Linguagens para ignorar (opcional)
            html, css, markdown