name: Update Tech Chart

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install linguist
        run: |
          sudo gem install github-linguist

      - name: Run linguist
        run: |
          linguist --json > languages.json
          cat languages.json

      - name: Generate chart with QuickChart
        run: |
          LANGS=$(jq -r 'to_entries | map("\(.key)") | join(",")' languages.json)
          VALUES=$(jq -r 'to_entries | map(.value) | join(",")' languages.json)

          echo "![Gráfico Tecnologias](https://quickchart.io/chart?c={type:'doughnut',data:{labels:[$LANGS],datasets:[{data:[$VALUES]}]}})" > chart.md

      - name: Update README.md
        run: |
          sed -i '/<!--TECH-CHART-START-->/,/<!--TECH-CHART-END-->/c\<!--TECH-CHART-START-->\n'$(cat chart.md)'\n<!--TECH-CHART-END-->' README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "update tech chart [skip ci]" || echo "No changes to commit"
          git push
